config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :goods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :price, :image_url)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goods/_form.html.slim
= form_for @good do |f|
  - if @good.errors.any?
    #error_explanation
      h2 = "#{pluralize(@good.errors.count, "error")} prohibited this good from being saved:"
      ul
        - @good.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :image_url
    = f.text_field :image_url
  .actions = f.submit

app/views/goods/edit.html.slim
h1 Editing good

== render 'form'

= link_to 'Show', @good
'  |
= link_to 'Back', goods_path

app/views/goods/index.html.slim
h1 Listing goods

table
  thead
    tr
      th Name
      th Price
      th Image url
      th
      th
      th

  tbody
    - @goods.each do |good|
      tr
        td = good.name
        td = good.price
        td = good.image_url
        td = link_to 'Show', good
        td = link_to 'Edit', edit_good_path(good)
        td = link_to 'Destroy', good, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Good', new_good_path

app/views/goods/new.html.slim
h1 New good

== render 'form'

= link_to 'Back', goods_path

app/views/goods/show.html.slim
p#notice = notice

p
  strong Name:
  = @good.name
p
  strong Price:
  = @good.price
p
  strong Image url:
  = @good.image_url

= link_to 'Edit', edit_good_path(@good)
'  |
= link_to 'Back', goods_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Zozoworld
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-dark.bg-primary
      = link_to 'ZOZOWORLD', '#', class: 'navbar-brand'
    .container
      = yield

app/views/shops/_form.html.slim
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      ul
        - @shop.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/shops/edit.html.slim
h1 Editing shop

== render 'form'

= link_to 'Show', @shop
'  |
= link_to 'Back', shops_path

app/views/shops/index.html.slim
h1 Listing shops

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @shops.each do |shop|
      tr
        td = shop.name
        td = link_to 'Show', shop
        td = link_to 'Edit', edit_shop_path(shop)
        td = link_to 'Destroy', shop, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.slim
h1 New shop

== render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.slim
p#notice = notice

p
  strong Name:
  = @shop.name

= link_to 'Edit', edit_shop_path(@shop)
'  |
= link_to 'Back', shops_path